### PR TITLE
added using_section to grammar.js and wrote tests

### PR DESCRIPTION
**Pull request by aMOPel**

### CODE REVIEW

**Review by alaviss — APPROVED** [review]

**Comment by aMOPel** [comment]
This time I used `npm run build`. And `npm install` says "up tp date".

**Comment by aMOPel** [comment]
feel free to fix it again

**Comment by alaviss** [comment]
> This time I used `npm run build`. And `npm install` says "up tp date".

That's very weird. What's the output of `npx tree-sitter -V` for you?

**Comment by aMOPel** [comment]
```
$ npx tree-sitter --version
tree-sitter 0.20.8 (d4c1bf7ce78051b7f4a381d1508d68928512ed5f)
```

**Comment by alaviss** [comment]
I managed to reproduce the issue with a clean clone.

Looks like a bug, I'll see what I can do.

**Comment by alaviss** [comment]
Can you try rebasing your PR?

**Comment by aMOPel** [comment]
didn't help I think

**Comment by alaviss** [comment]
So there seems to be a version mismatch: https://github.com/alaviss/tree-sitter-nim/actions/runs/6164463002/job/16730219989#step:5:5

> tree-sitter 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c)

Looking at https://github.com/tree-sitter/tree-sitter/releases/tag/v0.20.8, seems like they did a retag. `0c49d6745b3fc4822ab02e0018770cd6383a779c` is indeed the correct hash for 0.20.8, not `d4c1bf7ce78051b7f4a381d1508d68928512ed5f` but that's what reported by their linux x64 binaries.

Probably just an issue with their pipeline. I'll open an issue there and merge this PR anyways

**Pull request merged**
