### PR TITLE
change long string opening from regex to literal choice

### PR DESCRIPTION
**Pull request by alaviss**
Apparently this helps with writing injection queries.

Ref: https://github.com/alaviss/tree-sitter-nim/pull/32#issuecomment-1717850053

### CODE REVIEW

**Comment by alaviss** [comment]
@aMOPel can you test with this branch?

**Comment by aMOPel** [comment]
Already tested the exact thing locally. Works like a charm for me.

**Comment by alaviss** [comment]
Let me know if you're planning for any more changes before I cut 0.0.4

**Comment by aMOPel** [comment]
So far I'm fine. Gonna look into locals.scm next. Maybe some stuff comes up.

**Pull request merged**
