### PR TITLE
added string_content to string literals and comment_content to comment literals for injections queries

### PR DESCRIPTION
**Pull request by aMOPel**

### CODE REVIEW

**Comment by aMOPel** [comment]
gonna need your help for this one.

The test extras/Single-line comments breaks, since the parsing for the comments breaks when I extract the leading `#` and `##`.

Do you know how to do this?

**Comment by alaviss** [comment]
Do you actually need these? For example, nvim supports `#offset!` so you can skip the opening and closing marks.

Due to the structure of these nodes they're very annoying to have the structure split out. You lose a lot of guarantees when you split something out (ie. `extras` can show up between any two tokens, especially externalized ones).

And I've not have good experiences with `alias(repeat)`. It tends to generate multiples of the same node.

We can have `string_literal` be specialized into multiple kinds if it helps your queries (since different string types have different offsets).

**Comment by aMOPel** [comment]
> nvim supports offset

Source?

**Comment by alaviss** [comment]
> > nvim supports offset
> 
> Source?

[`:h treesitter-directive-offset!`](https://neovim.io/doc/user/treesitter.html#treesitter-directive-offset%21)

**Comment by aMOPel** [comment]
Great! Gonna look into that tomorrow

**Comment by alaviss** [comment]
It's probably because that part was a regex.

Maybe it'll work if we change it into a choice. There are only 3 of those anyways

**Comment by aMOPel** [comment]
Yep. Works great. You gonna commit that?

**Pull request closed without merging**
